//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.30 at 01:33:39 PM CST 
//


package com.kingshuk.schema.student;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for course.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="course">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="CSE"/>
 *     &lt;enumeration value="MECH"/>
 *     &lt;enumeration value="AUE"/>
 *     &lt;enumeration value="ECE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "course")
@XmlEnum
public enum Course {

    IT,
    CSE,
    MECH,
    AUE,
    ECE;

    public String value() {
        return name();
    }

    public static Course fromValue(String v) {
        return valueOf(v);
    }

}
