//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.30 at 12:34:57 PM CST 
//


package com.kingshuk.schema.student;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MinorSubjects complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MinorSubjects">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Maths" type="{http://kingshuk.com/schema/student.xsd}Subjects"/>
 *         &lt;element name="Automata" type="{http://kingshuk.com/schema/student.xsd}Subjects"/>
 *         &lt;element name="HTML" type="{http://kingshuk.com/schema/student.xsd}Subjects"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MinorSubjects", propOrder = {
    "html",
    "automata",
    "maths"
})
public class MinorSubjects
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "HTML")
    protected Subjects html;
    @XmlElement(name = "Automata")
    protected Subjects automata;
    @XmlElement(name = "Maths")
    protected Subjects maths;

    /**
     * Gets the value of the html property.
     * 
     * @return
     *     possible object is
     *     {@link Subjects }
     *     
     */
    public Subjects getHTML() {
        return html;
    }

    /**
     * Sets the value of the html property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subjects }
     *     
     */
    public void setHTML(Subjects value) {
        this.html = value;
    }

    /**
     * Gets the value of the automata property.
     * 
     * @return
     *     possible object is
     *     {@link Subjects }
     *     
     */
    public Subjects getAutomata() {
        return automata;
    }

    /**
     * Sets the value of the automata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subjects }
     *     
     */
    public void setAutomata(Subjects value) {
        this.automata = value;
    }

    /**
     * Gets the value of the maths property.
     * 
     * @return
     *     possible object is
     *     {@link Subjects }
     *     
     */
    public Subjects getMaths() {
        return maths;
    }

    /**
     * Sets the value of the maths property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subjects }
     *     
     */
    public void setMaths(Subjects value) {
        this.maths = value;
    }

}
